import Head from 'next/head'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Pratos do Dia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <main className={styles.main}>
        <section>
          <div className={styles.dubloCheedar}>
            <h1 className={styles.h1}>DUPLO CHEEDAR</h1>
            <h2 className={styles.h2}>R$25,00</h2>
          </div>
          <button className={styles.button}>MAIS INFORMAÇÕES</button>
        </section>

        <section>
          <div className={styles.MAC_CHEESE}>
            <h1 className={styles.h1}>MAC CHEESE</h1>
            <h2 className={styles.h2}>R$20,00</h2>
          </div>
          <button className={styles.button}>MAIS INFORMAÇÕES</button>
        </section>

        <section>
          <div className={styles.TORTA_DOCE}>
            <h1 className={styles.h1}>TORTA DOCE</h1>
            <h2 className={styles.h2}>R$10,00</h2>
          </div>
          <button className={styles.button}>MAIS INFORMAÇÕES</button>
        </section>
        
      </main>
    </>
  )
}
